### ISSUE TITLE
IndexError on startup 

### ISSUE THREAD

**Issue by avikj** [dhruvramani/Terminal-on-FB-Messenger#15]
When the application is run and no messages have been sent so far, there is an IndexError. It is fairly easy to avoid, by ensuring that you have sent at least one message to yourself before you run the script, but some users may not be able to decipher the issue. Here's the error message on Windows:

``` shell
Email : hiddenforprivacy@example.com
Password :
Loading...

Traceback (most recent call last):
  File "messengercmd.py", line 247, in <module>
    init()
  File "messengercmd.py", line 230, in init
    replyButton = [x for x in driver.find_elements_by_tag_name('input') if x.ge
_attribute('value') == 'Reply'][0]
IndexError: list index out of range

C:\>
```

**Comment by dhruvramani** [comment]
This is just beause of some network error being occurred, and the page hasn't loaded properly. Please re run the script and see if the error occurs again.

**Comment by dhruvramani** [comment]
HB
