### ISSUE TITLE
Add a disclaimer to README

### ISSUE THREAD

**Issue by fborcic** [dhruvramani/Terminal-on-FB-Messenger#5]
I suggest you add a disclaimer to README since the use of your script violates the facebook TOS:

> You will not collect users' content or information, or otherwise access Facebook, using automated means (such as harvesting bots, robots, spiders, or scrapers) without our prior permission.

**Comment by dhruvramani** [comment]
Thanks, I'll do that as soon as I get access to my dev machine.
