### ISSUE TITLE
File upload opens when entering any command

### ISSUE THREAD

**Issue by mmplisskin** [dhruvramani/Terminal-on-FB-Messenger#6]
Every time a command is entered File upload opens in firefox.

**Comment by dhruvramani** [comment]
Could you upload a screenshot of your terminal when this happens?

**Comment by mmplisskin** [comment]
<img width="646" alt="screen shot 2016-02-16 at 7 27 22 am" src="https://cloud.githubusercontent.com/assets/7832832/13080745/e387ba9a-d47e-11e5-9eb6-cf8590eb4aeb.png">

**Comment by dhruvramani** [comment]
I just committed code. Now it uses chrome, which makes the overall experience faster. Please try now and check

**Comment by mmplisskin** [comment]
Thanks, this seems to work better although now the driver cannot find a css element. Please see my pr.
